//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int LogID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public Nullable<byte> AuditStatus { get; set; }
        public string Remark { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ProductOrder ProductOrder { get; set; }
    }
}
