//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int Id { get; set; }
        public Nullable<int> DepId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Age { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual department department { get; set; }
    }
}
