//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.Role_Menu = new HashSet<Role_Menu>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public string ClassIntro { get; set; }
        public Nullable<int> Depth { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ParentPath { get; set; }
        public string LinkUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role_Menu> Role_Menu { get; set; }
    }
}
