//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductOrder()
        {
            this.AuditLog = new HashSet<AuditLog>();
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> StorageID { get; set; }
        public string OrderNum { get; set; }
        public string BuyType { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> AuditBy { get; set; }
        public Nullable<byte> OrderStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLog> AuditLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual Storage Storage { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
