//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class region
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> pid { get; set; }
        public string sname { get; set; }
        public Nullable<int> level { get; set; }
        public string citycode { get; set; }
        public string yzcode { get; set; }
        public string mername { get; set; }
        public Nullable<float> Lng { get; set; }
        public Nullable<float> Lat { get; set; }
        public string pinyin { get; set; }
    }
}
