//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Storage
    {
        public string StorageTypeName { get; set; }
        public int StorageID { get; set; }
        public Nullable<int> StorageTypeID { get; set; }
        public string StorageCode { get; set; }
        public string StorageName { get; set; }
        public Nullable<bool> StorageStatus { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
        public string StorageLocation { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UserName { get; set; }
    }
}
